{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .volume.name }}-pv
spec:
  capacity:
    storage: {{ .volume.storageCapacity }}
  volumeMode: {{ .volume.mode }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .volume.reclaimPolicy }}
  local:
    path: {{ .volume.localMountPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: youtrack-specific
              operator: In
              values:
                - localstore
{{- end }}
