{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .volume.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .volume.storage }}
  selector:
    matchExpressions:
      - key: youtrack-specific
        operator: In
        values:
          - localstore
{{- end }}
